allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true

  ignoreCves: []
patchedDependencies:
  '@radix-ui/react-compose-refs@1.1.2': patches/@radix-ui__react-compose-refs@1.1.2.patch
  '@radix-ui/react-compose-refs@1.1.3': patches/@radix-ui__react-compose-refs@1.1.3.patch
