import { test, expect } from '../fixtures/baseFixtures'
 
import fs from 'fs'
 
import path from 'path'

/**
 * Test Suite: Invalid Recipe Handling
 *
 * Tests how the application handles non-existent recipes:
 * - Shows loading skeleton initially (both static HTML and React)
 * - Attempts network fallback
 * - Shows 404 after timeout (5 seconds)
 * - Proper SEO meta tags for 404
 */

test.describe('Invalid Recipe Handling', () => {
  test('should have static HTML skeleton in source index.html', async () => {
    // This test checks that the source index.html includes the static skeleton
    // Note: index.html is generated by scripts/generate-index-html.js during build
    // In CI, if the file doesn't exist yet, we verify the generator function instead

    const sourcePath = path.join(process.cwd(), 'index.html')

    // Check if index.html exists (it's generated during build)
    if (!fs.existsSync(sourcePath)) {
      // In CI or before build, verify the generator function has the skeleton
      const { generateIndexHTML } = await import(
        '../../scripts/generate-index-html.js'
      )
      const generatedHtml = generateIndexHTML()

      // Verify the static skeleton HTML exists in generated output
      expect(generatedHtml).toContain('initial-skeleton')
      expect(generatedHtml).toContain('skeleton-box')
      expect(generatedHtml).toContain('animation: pulse')

      // Verify skeleton structure is present
      expect(generatedHtml).toContain('<!-- Initial loading skeleton')
      expect(generatedHtml).toContain(
        'This prevents 404 flash when sharing recipe links',
      )

      // Verify skeleton has content (header, image, meta placeholders)
      expect(generatedHtml).toContain('<!-- Header skeleton -->')
      expect(generatedHtml).toContain('<!-- Image skeleton -->')
      expect(generatedHtml).toContain('<!-- Meta info skeleton -->')
    } else {
      // If file exists, verify it directly
      const indexHtml = fs.readFileSync(sourcePath, 'utf-8')

      // Verify the static skeleton HTML exists in the source file
      expect(indexHtml).toContain('initial-skeleton')
      expect(indexHtml).toContain('skeleton-box')
      expect(indexHtml).toContain('animation: pulse')

      // Verify skeleton structure is present
      expect(indexHtml).toContain('<!-- Initial loading skeleton')
      expect(indexHtml).toContain(
        'This prevents 404 flash when sharing recipe links',
      )

      // Verify skeleton has content (header, image, meta placeholders)
      expect(indexHtml).toContain('<!-- Header skeleton -->')
      expect(indexHtml).toContain('<!-- Image skeleton -->')
      expect(indexHtml).toContain('<!-- Meta info skeleton -->')
    }
  })

  test('should show loading skeleton then 404 for non-existent recipe after timeout', async ({
    page,
    populatedDb,
  }) => {
    // Navigate to a non-existent recipe
    await page.goto('/recipe/this-recipe-does-not-exist-12345')

    // Should initially show loading skeleton
    const skeleton = page.locator('[data-testid="recipe-skeleton"]')
    await expect(skeleton).toBeVisible({ timeout: 2000 })

    // Should NOT show 404 immediately (should show skeleton during timeout)
    const notFoundText = page.getByText(/page introuvable|404/i)
    await expect(notFoundText).not.toBeVisible()

    // After 5+ seconds, should show 404
    // We wait slightly longer to account for processing time
    await expect(notFoundText).toBeVisible({ timeout: 7000 })

    // Skeleton should no longer be visible
    await expect(skeleton).not.toBeVisible()
  })

  test('should have proper SEO meta tags for 404 page', async ({
    page,
    populatedDb,
  }) => {
    // Navigate to a non-existent recipe and wait for 404
    await page.goto('/recipe/non-existent-recipe-slug')

    // Wait for 404 to appear (after timeout)
    await expect(page.getByText(/page introuvable|404/i)).toBeVisible({
      timeout: 7000,
    })

    // Check meta tags
    const title = await page.title()
    expect(title).toContain('Recette non trouvée')
    expect(title).toContain('Nos Recettes')
  })

  test('should show back to home button on 404 page', async ({
    page,
    populatedDb,
  }) => {
    // Navigate to a non-existent recipe and wait for 404
    await page.goto('/recipe/invalid-slug-abc123')

    // Wait for 404 to appear
    await expect(page.getByText(/page introuvable|404/i)).toBeVisible({
      timeout: 7000,
    })

    // Should have a link back to home
    const homeLink = page.getByRole('link', { name: /retour.*accueil|home/i })
    await expect(homeLink).toBeVisible()

    // Clicking should navigate home
    await homeLink.click()
    await expect(page).toHaveURL('/')
  })

  test('should handle direct URL access to non-existent recipe', async ({
    page,
    populatedDb,
  }) => {
    // Directly navigate to invalid URL (simulates sharing a broken link)
    await page.goto('/recipe/broken-share-link-xyz')

    // Should show skeleton first
    await expect(page.locator('[data-testid="recipe-skeleton"]')).toBeVisible({
      timeout: 2000,
    })

    // Then 404 after timeout
    await expect(page.getByText(/page introuvable|404/i)).toBeVisible({
      timeout: 7000,
    })
  })

  test('should not flash 404 during normal recipe load', async ({
    page,
    populatedDb,
  }) => {
    // Navigate to a VALID recipe
    await page.goto('/')
    const firstCard = page.locator('[data-testid="recipe-card"]').first()
    const href = await firstCard.getAttribute('href')

    // Navigate to valid recipe
    await page.goto(href ?? '')

    // Should never show 404 text during normal load
    const notFoundText = page.getByText(/page introuvable|404/i)

    // Wait for recipe to load (title should appear)
    await expect(page.locator('h1')).toBeVisible({ timeout: 10000 })

    // 404 should never have appeared
    await expect(notFoundText).not.toBeVisible()
  })

  test('should reset timeout when navigating between recipes', async ({
    page,
    populatedDb,
  }) => {
    // First navigate to invalid recipe
    await page.goto('/recipe/invalid-recipe-1')

    // Wait a bit but not full timeout
    await page.waitForTimeout(2000)

    // Navigate to another invalid recipe
    await page.goto('/recipe/invalid-recipe-2')

    // Skeleton should be visible again (timeout reset)
    await expect(page.locator('[data-testid="recipe-skeleton"]')).toBeVisible()

    // 404 should not appear immediately (timeout restarted)
    const notFoundText = page.getByText(/page introuvable|404/i)
    await expect(notFoundText).not.toBeVisible()

    // Wait for new timeout to complete
    await expect(notFoundText).toBeVisible({ timeout: 7000 })
  })
})
