import { Recipe } from '@/types/recipe'

export const bouillonAFondueThai: Recipe = {
  id: 'bouillon-a-fondue-thai',
  title: 'Bouillon à fondue Thaï',
  description:
    'Un bouillon épicé et parfumé pour fondue, idéal pour accompagner fruits de mer, viande ou tofu.',
  categories: ['Soupes', 'Plats principaux'],
  prepTime: { min: 20, max: 20 },
  cookTime: { min: 20, max: 20 },
  servings: 0,
  difficulty: 'Facile',
  ingredients: [
    '1 oignon',
    '1 gousse ail, pressée',
    '1 morceau gingembre, frais, haché',
    '1 c.à soupe (15 ml) pâte de piments, fraîche',
    '1 limette',
    '2 conserves (14 oz; 398 ml chacune) de lait de coco',
    '1 5/8 tasse (410 ml) bouillon de poulet',
    '3 branches coriandre, fraîche',
    '3 c.à soupe (45 ml) huile harachide',
    'Sel',
    'Poivre',
  ],
  instructions: [
    "Émincer l'oignon.",
    "Faire revenir dans un caquelon avec 1 c.à soupe (15 ml) d'huile.",
    'Râper le gingembre.',
    "Presser l'ail.",
    'Ajouter ces deux ingrédients dans le caquelon.',
    'Faire revenir légèrement.',
    'Ajouter la pâte de piments, un zeste et le jus de la limette.',
    'Mélanger.',
    'Ajouter le lait de coco, le bouillon de poulet et la coriandre.',
    'Mélanger.',
    'Saler et poivrer au goût.',
    "Ajouter le reste de l'huile.",
    'Porter à ébullition pendant 2 à 3 min.',
    'Déposer sur le réchaud.',
    'Servir avec des pinces et des queues de homard, des pattes de crabe, des crevettes décortiquées, du boeuf, du poulet ou du tofu en cubes.',
  ],
  tags: ['épicé', 'fondue', 'thaï'],
  slug: 'bouillon-a-fondue-thai',
}
