import { Recipe } from '@/types/recipe'

export const cariDePouletFrais: Recipe = {
  id: 'cari-de-poulet-frais',
  title: 'Cari de poulet frais',
  description:
    "Un curry de poulet parfumé avec un mélange d'épices, lait de coco, tomates et aromates, servi avec du riz basmati.",
  categories: ['Plats principaux', 'Végétarien'],
  prepTime: { min: 25, max: 25 },
  cookTime: { min: 20, max: 20 },
  servings: 4,
  difficulty: 'Facile',
  ingredients: [
    "Mélange d'épice au cari",
    '15 ml de gingembre frais, râpé',
    '2 gousses d’ail, hachées',
    '2,5 ml de cumin',
    '2,5 ml de curcuma',
    '2,5 ml de cannelle',
    '5 ml de poudre de cari',
    '5 ml de coriandre moulue',
    '5 ml de sel',
    '30 ml d’huile d’olive',
    '4 poitrines de poulet désossées, coupées en gros cubes',
    'Sel et poivre',
    '1 oignon, haché',
    '1 boîte de lait de coco bien brassé',
    '30 ml de pâte de tomates',
    '1 tasse de tomates fraîches, en dés',
    '1 pomme verte, en fines allumettes',
    'Basilic Thai ou basilic régulier ou coriandre, ciselé',
    '1 piment chili, émincé finement',
    '1 lime, coupée en quartiers',
  ],
  instructions: [
    "Dans un petit bol, bien mélanger tous les ingrédients du mélange d'épice au cari. Réserver.",
    'Dans une grande poêle, à feu moyen-élevé, saisir les cubes de poulet assaisonnés de sel et de poivre rapidement dans l’huile. Réserver dans une assiette.',
    'Ajouter les oignons et un peu d’huile au besoin, poursuivre la cuisson jusqu’à ce qu’ils soient tendres.',
    "Ajouter la mélange d'épice de cari et poursuivre la cuisson 2 minutes en mélangeant bien.",
    'Ajouter le lait de coco, la pâte de tomate et bien mélanger.',
    'Ajouter le poulet réservé, les dés de tomates et poursuivre la cuisson encore 10 minutes à feu très doux.',
    'Rectifier l’assaisonnement.',
    'Servir garni de pommes allumettes, de basilic et de piments chili.',
  ],
  tags: ['épicé', 'curry', 'poulet'],
  slug: 'cari-de-poulet-frais',
}
