import { Recipe } from '@/types/recipe'

export const filetDePorcPoireEtVinRouge: Recipe = {
  id: 'filet-de-porc-poire-et-vin-rouge',
  title: 'filet de porc poire et vin rouge',
  description:
    "Une recette savoureuse de filet de porc accompagné de poires caramélisées au vin rouge, nappé d'une sauce demi-glace et crème.",
  categories: ['Vollaille', 'Plats principaux'],
  prepTime: { min: 15, max: 15 },
  cookTime: { min: 20, max: 20 },
  servings: 4,
  difficulty: 'Facile',
  ingredients: [
    '2 filets de porc',
    'Sel et poivre au goût',
    '3 poire épluchées et coupées en quartiers',
    '125 ml (1/2 tasse) de vin rouge',
    '1 boîte de 284 ml de sauce demi-glace',
    '80 ml (1/3 de tasse) de crème à cuisson 15%',
    '30 ml (2 c. à soupe) d’huile d’olive',
    '1 oignon émincé',
    '30 ml (2 c. à soupe) de sucre',
  ],
  instructions: [
    'Saler et poivrer le filet de porc.',
    'Dans une grande poêle, chauffer l’huile à feu moyen.',
    'Dorer le filet de porc sur toutes les faces.',
    'Retirer le filet de la poêle et réserver.',
    'Dans la même poêle, faire caraméliser les poires avec l’oignon et le sucre de 1 à 2 minutes.',
    'Verser le vin rouge et porter à ébullition.',
    'Verser la sauce demi-glace puis remettre le filet de porc dans la poêle.',
    'Couvrir et cuire 15 minutes à feu doux-moyen.',
    'Verser la crème et prolonger la cuisson de 2 à 3 minutes.',
    'Retirer le filet et déposer dans une assiette.',
    'Couvrir d’une feuille de papier d’aluminium et laisser reposer 8 minutes avant de trancher.',
    'Servir avec la sauce.',
  ],
  tags: ['vin rouge', 'poire', 'sauce demi-glace'],
  slug: 'filet-de-porc-poire-et-vin-rouge',
}
