import { Recipe } from '@/types/recipe';

export const pouletALaJamaicaineFarciAuFromageMontereyJackHabanero: Recipe = {
  id: 'poulet-a-la-jamaicaine-farci-au-fromage-monterey-jack-habanero',
  title: 'Poulet à la jamaïcaine farci au fromage Monterey Jack Habanero',
  description: 'Recette pleine de saveur.',
  categories: ['Vollaille', 'Plats principaux'],
  prepTime: 30,
  cookTime: 30,
  servings: 4,
  difficulty: 'Facile',
  ingredients: [
    '125 g d’un bloc de fromage Monterey Jack Habanero, coupé en 4 bâtonnets',
    '1/3 tasse d’huile de canola',
    '1 c. à soupe de sauce soya',
    '1 c. à soupe de thym frais, haché finement',
    '2 gousses d’ail, émincées',
    '1 c. à soupe de gingembre frais, émincé',
    '1 c. à thé chacun de piment de la Jamaïque et de poudre de chili',
    '1 c. à thé de poivre',
    '1 c. à thé de cassonade',
    '1/2 c. à thé de sel',
    '1/4 c. à thé de cannelle',
    '1/4 c. à thé de piment de cayenne moulus',
    '4 poitrines de poulet',
    '4 quartiers de lime, pour servir',
    '1 c. à soupe d’huile de canola',
    '1 oignon, coupé en dés',
    '2 gousses d’ail, émincées',
    '1 c. à soupe de gingembre frais, émincé',
    '1 c. à soupe de thym frais, finement haché',
    '2 c. à thé de piment de la Jamaïque',
    '½ c. à thé de poivre de Cayenne',
    '1 tasse de riz basmati',
    '½ c. à thé chacun de sel et de poivre',
    '1 boîte de lait de coco',
    '1 tasse de bouillon de poulet réduit en sodium',
    '1 boîte de haricots noirs, égouttés et rincés',
    '2 feuilles de laurier',
    '2 c. à soupe de coriandre fraîche, finement hachée'
  ],
  instructions: [
    'Dans un grand bol ou un sac en plastique refermable, mélanger 3 c. à soupe d’huile, la sauce soya, le thym, l’ail, le gingembre, le piment de la Jamaïque, la poudre de chili, le poivre, la cassonade, le sel, la cannelle et le piment de cayenne.',
    'Ajouter le poulet et bien enrober des épices. Réfrigérer pendant au moins 1 heure, ou jusqu’à 4 heures.',
    'Retirer le poulet de la marinade et jeter la marinade.',
    'Préchauffer le four à 400°F.',
    'À l’aide d’un couteau à éplucher bien affûté, couper chaque poitrine de poulet à l’horizontale, sans couper au complet, afin de créer une pochette dans chaque poitrine.',
    'Farcir chaque pochette avec un bâtonnet de fromage.',
    'Dans un poêlon allant au four, chauffer le reste d’huile à feu moyen, puis saisir le poulet de 2 à 3 minutes de chaque côté, ou jusqu’à ce que la viande soit dorée de tous les côtés.',
    'Mettre le poêlon au four et cuire de 12 à 15 minutes, ou jusqu’à ce que le poulet soit bien cuit.',
    'Entre-temps, chauffer l’huile dans une casserole à feu moyen; faire revenir les oignons, l’ail, le gingembre, le thym, le piment de la Jamaïque et le piment de cayenne pendant environ 3 minutes, ou jusqu’à ce que les oignons soient légèrement ramollis.',
    'Ajouter le riz, le sel et le poivre en remuant jusqu’à ce que le riz soit bien enrobé.',
    'Ajouter le lait de coco, le bouillon de poulet, les haricots et les feuilles de laurier en remuant, puis porter à ébullition.',
    'Réduire à feu doux; couvrir et laisser mijoter de 15 à 18 minutes, ou jusqu’à ce que le riz soit tendre et qu’il ait absorbé presque tout le liquide.',
    'Retirer du feu, couvrir et laisser reposer 5 minutes.',
    'Retirer et jeter les feuilles de laurier.',
    'Ajouter la coriandre en remuant.',
    'Servir le poulet sur un lit de riz et de haricots, puis garnir de quartiers de lime.'
  ],
  tags: ['jamaïque', 'marinade', 'grill'],
  source: 'David Cloutier',
  slug: 'poulet-a-la-jamaicaine-farci-au-fromage-monterey-jack-habanero'
};
